#!/usr/bin/env bash
# One-command local setup for textile-pos.
#
# Usage:
#   npm run setup                       # interactive prompts where needed
#   npm run setup -- --yes              # non-interactive; safe defaults + generated secrets
#   npm run setup -- --backend-port 5002 --frontend-port 5174
#
# See README.md for the full list of supported flags.

set -Eeuo pipefail

# Resolve repo root (script lives in <root>/scripts/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

BACKEND_ENV="$ROOT_DIR/backend/.env"
FRONTEND_ENV="$ROOT_DIR/frontend/.env"
DOCKER_ENV="$ROOT_DIR/docker/.env"
DOCKER_COMPOSE_FILE="$ROOT_DIR/docker/docker-compose.yml"

# ──────────────────────────────────────────────────────────────────────────────
# Output helpers
# ──────────────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'
  C_BLUE=$'\033[34m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'; C_DIM=$'\033[2m'
else
  C_RESET=""; C_BOLD=""; C_BLUE=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_DIM=""
fi
say()  { printf "%s\n" "$*"; }
info() { printf "${C_BLUE}▸${C_RESET} %s\n" "$*"; }
ok()   { printf "${C_GREEN}✓${C_RESET} %s\n" "$*"; }
warn() { printf "${C_YELLOW}!${C_RESET} %s\n" "$*" >&2; }
err()  { printf "${C_RED}✗${C_RESET} %s\n" "$*" >&2; }
step() { printf "\n${C_BOLD}${C_BLUE}== %s ==${C_RESET}\n" "$*"; }

on_error() {
  err "Setup failed at line $1."
  cat <<EOF >&2

Common fixes:
  - Docker not running               → start Docker Desktop, then re-run.
  - Port already used                → re-run with --mysql-port / --backend-port / --frontend-port.
  - MySQL connection failed          → check docker/.env credentials and 'docker compose -f docker/docker-compose.yml ps'.
  - Prisma migration failed          → 'cd backend && npx prisma migrate status' for details.
  - Permission denied on setup.sh    → 'chmod +x scripts/setup.sh' or run 'bash scripts/setup.sh'.
EOF
}
trap 'on_error $LINENO' ERR

# ──────────────────────────────────────────────────────────────────────────────
# Defaults
# ──────────────────────────────────────────────────────────────────────────────
DEFAULT_MYSQL_PORT=3306
DEFAULT_BACKEND_PORT=5001
DEFAULT_FRONTEND_PORT=5173
DEFAULT_DB_NAME="textile_pos"
DEFAULT_DB_USER="textile_pos"
DEFAULT_BASE_CURRENCY="AED"
DEFAULT_COMPANY_NAME="Al Noor Textile Trading"
DEFAULT_ADMIN_USERNAME="admin"
DEFAULT_ADMIN_EMAIL="admin@textilepos.local"
DEFAULT_ADMIN_NAME="Administrator"

# Inputs (empty means "ask / derive").
MYSQL_PORT=""
BACKEND_PORT=""
FRONTEND_PORT=""
DB_NAME=""
DB_USER=""
DB_PASSWORD=""
DB_ROOT_PASSWORD=""
ADMIN_NAME=""
ADMIN_EMAIL=""
ADMIN_USERNAME=""
ADMIN_PASSWORD=""
BASE_CURRENCY=""
COMPANY_NAME=""
ASSUME_YES=false
SKIP_INSTALL=false
SKIP_DOCKER=false
SKIP_MIGRATE=false
SKIP_SEED=false
RESET_ADMIN_PASSWORD=false

ADMIN_PASSWORD_AUTOGENERATED=false

# ──────────────────────────────────────────────────────────────────────────────
# Flag parsing
# ──────────────────────────────────────────────────────────────────────────────
print_help() {
  cat <<EOF
textile-pos setup script

Usage: npm run setup -- [flags]

Required-when-empty inputs (prompted interactively unless --yes is passed):
  --mysql-port <n>          MySQL host port    (default $DEFAULT_MYSQL_PORT)
  --backend-port <n>        Backend HTTP port  (default $DEFAULT_BACKEND_PORT)
  --frontend-port <n>       Frontend dev port  (default $DEFAULT_FRONTEND_PORT)
  --db-name <name>          Database name      (default $DEFAULT_DB_NAME)
  --db-user <name>          DB user            (default $DEFAULT_DB_USER)
  --db-password <pw>        DB password        (generated if missing)
  --db-root-password <pw>   MySQL root pw      (generated if missing)
  --admin-name <name>       Admin display name (default $DEFAULT_ADMIN_NAME)
  --admin-email <email>     Admin email        (default $DEFAULT_ADMIN_EMAIL)
  --admin-username <u>      Admin username     (default $DEFAULT_ADMIN_USERNAME)
  --admin-password <pw>     Admin password     (generated if missing)
  --base-currency <code>    Base currency      (default $DEFAULT_BASE_CURRENCY)
  --company-name <name>     Shop / company     (default "$DEFAULT_COMPANY_NAME")

Behaviour flags:
  --yes                     Non-interactive; use defaults / generated values.
  --skip-install            Skip npm install steps.
  --skip-docker             Skip docker compose up / health check.
  --skip-migrate            Skip prisma migrate deploy.
  --skip-seed               Skip prisma db seed.
  --reset-admin-password    Force-update existing admin password to --admin-password.
  -h | --help               Show this help.
EOF
}

require_value() {
  if [ -z "${2-}" ] || [[ "${2}" == --* ]]; then
    err "Flag $1 requires a value."
    exit 2
  fi
}

while [ $# -gt 0 ]; do
  case "$1" in
    --mysql-port)            require_value "$1" "${2-}"; MYSQL_PORT="$2"; shift 2 ;;
    --backend-port)          require_value "$1" "${2-}"; BACKEND_PORT="$2"; shift 2 ;;
    --frontend-port)         require_value "$1" "${2-}"; FRONTEND_PORT="$2"; shift 2 ;;
    --db-name)               require_value "$1" "${2-}"; DB_NAME="$2"; shift 2 ;;
    --db-user)               require_value "$1" "${2-}"; DB_USER="$2"; shift 2 ;;
    --db-password)           require_value "$1" "${2-}"; DB_PASSWORD="$2"; shift 2 ;;
    --db-root-password)      require_value "$1" "${2-}"; DB_ROOT_PASSWORD="$2"; shift 2 ;;
    --admin-name)            require_value "$1" "${2-}"; ADMIN_NAME="$2"; shift 2 ;;
    --admin-email)           require_value "$1" "${2-}"; ADMIN_EMAIL="$2"; shift 2 ;;
    --admin-username)        require_value "$1" "${2-}"; ADMIN_USERNAME="$2"; shift 2 ;;
    --admin-password)        require_value "$1" "${2-}"; ADMIN_PASSWORD="$2"; shift 2 ;;
    --base-currency)         require_value "$1" "${2-}"; BASE_CURRENCY="$2"; shift 2 ;;
    --company-name)          require_value "$1" "${2-}"; COMPANY_NAME="$2"; shift 2 ;;
    --yes)                   ASSUME_YES=true; shift ;;
    --skip-install)          SKIP_INSTALL=true; shift ;;
    --skip-docker)           SKIP_DOCKER=true; shift ;;
    --skip-migrate)          SKIP_MIGRATE=true; shift ;;
    --skip-seed)             SKIP_SEED=true; shift ;;
    --reset-admin-password)  RESET_ADMIN_PASSWORD=true; shift ;;
    -h|--help)               print_help; exit 0 ;;
    *) err "Unknown argument: $1"; print_help; exit 2 ;;
  esac
done

# ──────────────────────────────────────────────────────────────────────────────
# Prerequisites
# ──────────────────────────────────────────────────────────────────────────────
step "Checking prerequisites"
need_bin() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Required command not found: $1"
    exit 1
  fi
  ok "$1 found"
}
need_bin node
need_bin npm

if ! $SKIP_DOCKER; then
  need_bin docker
  if ! docker compose version >/dev/null 2>&1; then
    err "'docker compose' v2 plugin is required. Update Docker Desktop or install the compose plugin."
    exit 1
  fi
  ok "docker compose found"

  if ! docker info >/dev/null 2>&1; then
    err "Docker is installed but not running. Start Docker Desktop and re-run."
    exit 1
  fi
  ok "docker daemon reachable"
fi

# ──────────────────────────────────────────────────────────────────────────────
# Interactive prompts (only if missing AND --yes is not set AND we have a tty)
# ──────────────────────────────────────────────────────────────────────────────
has_tty() { [ -t 0 ]; }
prompt_value() {
  # $1=var name to set, $2=label, $3=default value
  local __var="$1" __label="$2" __default="$3" __input=""
  if $ASSUME_YES || ! has_tty; then
    eval "$__var=\"\${$__var:-$__default}\""
    return
  fi
  local __current; eval "__current=\"\${$__var-}\""
  if [ -n "$__current" ]; then return; fi
  read -r -p "$__label [$__default]: " __input || true
  eval "$__var=\"\${__input:-$__default}\""
}

prompt_password() {
  # $1=var name, $2=label
  local __var="$1" __label="$2" __input="" __confirm=""
  if $ASSUME_YES || ! has_tty; then return; fi
  local __current; eval "__current=\"\${$__var-}\""
  if [ -n "$__current" ]; then return; fi
  while true; do
    read -r -s -p "$__label (min 8 chars, blank = auto-generate): " __input; echo
    if [ -z "$__input" ]; then eval "$__var=\"\""; return; fi
    if [ "${#__input}" -lt 8 ]; then warn "Too short, try again."; continue; fi
    read -r -s -p "Confirm: " __confirm; echo
    if [ "$__input" != "$__confirm" ]; then warn "Did not match, try again."; continue; fi
    eval "$__var=\"$__input\""
    return
  done
}

step "Collecting configuration"
prompt_value    MYSQL_PORT       "MySQL host port"        "$DEFAULT_MYSQL_PORT"
prompt_value    BACKEND_PORT     "Backend HTTP port"      "$DEFAULT_BACKEND_PORT"
prompt_value    FRONTEND_PORT    "Frontend dev port"      "$DEFAULT_FRONTEND_PORT"
prompt_value    DB_NAME          "Database name"          "$DEFAULT_DB_NAME"
prompt_value    DB_USER          "Database user"          "$DEFAULT_DB_USER"
prompt_password DB_PASSWORD      "Database password"
prompt_password DB_ROOT_PASSWORD "MySQL root password"
prompt_value    COMPANY_NAME     "Company / shop name"    "$DEFAULT_COMPANY_NAME"
prompt_value    BASE_CURRENCY    "Base currency code"     "$DEFAULT_BASE_CURRENCY"
prompt_value    ADMIN_NAME       "Admin display name"     "$DEFAULT_ADMIN_NAME"
prompt_value    ADMIN_USERNAME   "Admin username"         "$DEFAULT_ADMIN_USERNAME"
prompt_value    ADMIN_EMAIL      "Admin email"            "$DEFAULT_ADMIN_EMAIL"
prompt_password ADMIN_PASSWORD   "Admin password"

# Apply final fall-through defaults (covers --yes / non-tty paths).
MYSQL_PORT="${MYSQL_PORT:-$DEFAULT_MYSQL_PORT}"
BACKEND_PORT="${BACKEND_PORT:-$DEFAULT_BACKEND_PORT}"
FRONTEND_PORT="${FRONTEND_PORT:-$DEFAULT_FRONTEND_PORT}"
DB_NAME="${DB_NAME:-$DEFAULT_DB_NAME}"
DB_USER="${DB_USER:-$DEFAULT_DB_USER}"
ADMIN_NAME="${ADMIN_NAME:-$DEFAULT_ADMIN_NAME}"
ADMIN_EMAIL="${ADMIN_EMAIL:-$DEFAULT_ADMIN_EMAIL}"
ADMIN_USERNAME="${ADMIN_USERNAME:-$DEFAULT_ADMIN_USERNAME}"
BASE_CURRENCY="$(echo "${BASE_CURRENCY:-$DEFAULT_BASE_CURRENCY}" | tr '[:lower:]' '[:upper:]')"
COMPANY_NAME="${COMPANY_NAME:-$DEFAULT_COMPANY_NAME}"

# ──────────────────────────────────────────────────────────────────────────────
# Secret generation
# ──────────────────────────────────────────────────────────────────────────────
gen_secret() {
  # 24 alnum chars — URL-safe so DATABASE_URL and other strings don't need encoding.
  LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-24}"
}

[ -z "$DB_PASSWORD" ]      && DB_PASSWORD="$(gen_secret 24)"          && info "Generated random DB password."
[ -z "$DB_ROOT_PASSWORD" ] && DB_ROOT_PASSWORD="$(gen_secret 24)"     && info "Generated random MySQL root password."
JWT_SECRET="$(gen_secret 48)"
SESSION_SECRET="$(gen_secret 48)"

if [ -z "$ADMIN_PASSWORD" ]; then
  ADMIN_PASSWORD="$(gen_secret 16)"
  ADMIN_PASSWORD_AUTOGENERATED=true
elif [ "${#ADMIN_PASSWORD}" -lt 8 ]; then
  err "Admin password must be at least 8 characters."
  exit 2
fi

# ──────────────────────────────────────────────────────────────────────────────
# Port availability — auto-pick alternates if requested ones are busy
# ──────────────────────────────────────────────────────────────────────────────
port_in_use() {
  local p="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -i "tcp:$p" -sTCP:LISTEN >/dev/null 2>&1 && return 0
    return 1
  fi
  # Fallback: try /dev/tcp (bash-builtin). 0 = open (in use).
  ( exec 3<>"/dev/tcp/127.0.0.1/$p" ) >/dev/null 2>&1 && { exec 3>&-; return 0; }
  return 1
}

resolve_port() {
  # $1=label, $2=requested port -> echoes chosen port
  local label="$1" requested="$2" port="$2" tries=0
  while port_in_use "$port"; do
    warn "Port $port is busy. Trying $((port+1))…" >&2
    port=$((port+1)); tries=$((tries+1))
    if [ $tries -ge 50 ]; then
      err "Could not find a free $label port near $requested."
      exit 1
    fi
  done
  if [ "$port" != "$requested" ]; then
    warn "$label port $requested unavailable — using $port instead." >&2
  fi
  echo "$port"
}

step "Resolving ports"
MYSQL_PORT="$(resolve_port "MySQL"    "$MYSQL_PORT")"
BACKEND_PORT="$(resolve_port "Backend" "$BACKEND_PORT")"
FRONTEND_PORT="$(resolve_port "Frontend" "$FRONTEND_PORT")"
ok "MySQL    → $MYSQL_PORT"
ok "Backend  → $BACKEND_PORT"
ok "Frontend → $FRONTEND_PORT"

# ──────────────────────────────────────────────────────────────────────────────
# .env writers — preserve unrelated existing keys
# ──────────────────────────────────────────────────────────────────────────────
upsert_env_var() {
  local file="$1" key="$2" value="$3"
  mkdir -p "$(dirname "$file")"
  touch "$file"
  if grep -qE "^${key}=" "$file" 2>/dev/null; then
    awk -v k="$key" -v v="$value" 'BEGIN{FS="="; OFS=""}
      {
        if (index($0, k"=") == 1) { print k"="v } else { print $0 }
      }' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

step "Writing environment files"

# DATABASE_URL — values are URL-safe alnum, no encoding needed.
DATABASE_URL="mysql://${DB_USER}:${DB_PASSWORD}@localhost:${MYSQL_PORT}/${DB_NAME}"

# backend/.env
upsert_env_var "$BACKEND_ENV" "NODE_ENV"                  "development"
upsert_env_var "$BACKEND_ENV" "PORT"                      "$BACKEND_PORT"
upsert_env_var "$BACKEND_ENV" "DATABASE_URL"              "\"$DATABASE_URL\""
upsert_env_var "$BACKEND_ENV" "JWT_SECRET"                "\"$JWT_SECRET\""
upsert_env_var "$BACKEND_ENV" "JWT_EXPIRES_IN"            "8h"
upsert_env_var "$BACKEND_ENV" "SESSION_SECRET"            "\"$SESSION_SECRET\""
upsert_env_var "$BACKEND_ENV" "CORS_ORIGIN"               "http://localhost:${FRONTEND_PORT}"
upsert_env_var "$BACKEND_ENV" "STORAGE_PATH"              "./storage"
upsert_env_var "$BACKEND_ENV" "BASE_CURRENCY_CODE"        "$BASE_CURRENCY"
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_NAME"           "\"$ADMIN_NAME\""
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_USERNAME"       "$ADMIN_USERNAME"
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_EMAIL"          "$ADMIN_EMAIL"
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_PASSWORD"       "\"$ADMIN_PASSWORD\""
upsert_env_var "$BACKEND_ENV" "SEED_COMPANY_NAME"         "\"$COMPANY_NAME\""
upsert_env_var "$BACKEND_ENV" "SEED_BASE_CURRENCY"        "$BASE_CURRENCY"
upsert_env_var "$BACKEND_ENV" "SEED_RESET_ADMIN_PASSWORD" "$([ "$RESET_ADMIN_PASSWORD" = true ] && echo true || echo false)"
ok "Wrote $BACKEND_ENV"

# frontend/.env
upsert_env_var "$FRONTEND_ENV" "VITE_API_URL"       "/api/v1"
upsert_env_var "$FRONTEND_ENV" "VITE_API_BASE_URL"  "http://localhost:${BACKEND_PORT}/api/v1"
upsert_env_var "$FRONTEND_ENV" "VITE_BACKEND_PORT"  "$BACKEND_PORT"
ok "Wrote $FRONTEND_ENV"

# docker/.env
upsert_env_var "$DOCKER_ENV" "MYSQL_DATABASE"       "$DB_NAME"
upsert_env_var "$DOCKER_ENV" "MYSQL_USER"           "$DB_USER"
upsert_env_var "$DOCKER_ENV" "MYSQL_PASSWORD"       "$DB_PASSWORD"
upsert_env_var "$DOCKER_ENV" "MYSQL_ROOT_PASSWORD"  "$DB_ROOT_PASSWORD"
upsert_env_var "$DOCKER_ENV" "MYSQL_PORT"           "$MYSQL_PORT"
ok "Wrote $DOCKER_ENV"

# ──────────────────────────────────────────────────────────────────────────────
# Install dependencies
# ──────────────────────────────────────────────────────────────────────────────
if ! $SKIP_INSTALL; then
  step "Installing dependencies (root → workspaces)"
  (cd "$ROOT_DIR" && npm install)
  ok "Dependencies installed"
else
  info "Skipping npm install (--skip-install)."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Docker MySQL
# ──────────────────────────────────────────────────────────────────────────────
if ! $SKIP_DOCKER; then
  step "Starting MySQL via docker compose"
  (cd "$ROOT_DIR/docker" && docker compose up -d)

  info "Waiting for MySQL to become healthy…"
  CID=""; tries=0
  while [ $tries -lt 60 ]; do
    CID="$(cd "$ROOT_DIR/docker" && docker compose ps -q db 2>/dev/null || true)"
    if [ -n "$CID" ]; then
      HEALTH="$(docker inspect --format='{{.State.Health.Status}}' "$CID" 2>/dev/null || echo "unknown")"
      if [ "$HEALTH" = "healthy" ]; then ok "MySQL is healthy."; break; fi
    fi
    tries=$((tries+1)); sleep 2
  done
  if [ "${HEALTH:-}" != "healthy" ]; then
    err "MySQL did not become healthy in time. Check 'docker compose -f docker/docker-compose.yml logs db'."
    exit 1
  fi
else
  info "Skipping docker compose (--skip-docker)."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Prisma: generate → migrate deploy → seed
# ──────────────────────────────────────────────────────────────────────────────
step "Generating Prisma client"
(cd "$ROOT_DIR/backend" && npx prisma generate)
ok "Prisma client generated"

if ! $SKIP_MIGRATE; then
  step "Applying database migrations (prisma migrate deploy)"
  (cd "$ROOT_DIR/backend" && npx prisma migrate deploy)
  ok "Migrations applied"
else
  info "Skipping migrations (--skip-migrate)."
fi

if ! $SKIP_SEED; then
  step "Seeding standard data"
  (cd "$ROOT_DIR/backend" && npx prisma db seed)
  ok "Seed complete"
else
  info "Skipping seed (--skip-seed)."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────────────
step "All done"
cat <<EOF
${C_BOLD}Service URLs${C_RESET}
  Frontend:  http://localhost:${FRONTEND_PORT}
  Backend:   http://localhost:${BACKEND_PORT}/api/v1
  MySQL:     localhost:${MYSQL_PORT}  (db: ${DB_NAME}, user: ${DB_USER})

${C_BOLD}Generated files${C_RESET}
  - backend/.env
  - frontend/.env
  - docker/.env

${C_BOLD}Next step${C_RESET}
  npm run dev
EOF

if $ADMIN_PASSWORD_AUTOGENERATED; then
  echo
  warn "An admin password was auto-generated. Save it now — it is shown once."
  echo "${C_BOLD}  username: ${ADMIN_USERNAME}"
  echo "  password: ${ADMIN_PASSWORD}${C_RESET}"
fi
