#!/usr/bin/env bash
# One-command local setup for textile-pos.
#
# Usage:
#   npm run setup                       # interactive prompts where needed
#   npm run setup -- --yes              # non-interactive; safe defaults + generated secrets
#   npm run setup -- --backend-port 5002 --frontend-port 5174
#
# See README.md for the full list of supported flags.

set -Eeuo pipefail

# Resolve repo root (script lives in <root>/scripts/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

BACKEND_ENV="$ROOT_DIR/backend/.env"
FRONTEND_ENV="$ROOT_DIR/frontend/.env"
DOCKER_ENV="$ROOT_DIR/docker/.env"
DOCKER_COMPOSE_FILE="$ROOT_DIR/docker/docker-compose.yml"

# ──────────────────────────────────────────────────────────────────────────────
# Output helpers
# ──────────────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'
  C_BLUE=$'\033[34m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'; C_DIM=$'\033[2m'
else
  C_RESET=""; C_BOLD=""; C_BLUE=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_DIM=""
fi
say()  { printf "%s\n" "$*"; }
info() { printf "${C_BLUE}▸${C_RESET} %s\n" "$*"; }
ok()   { printf "${C_GREEN}✓${C_RESET} %s\n" "$*"; }
warn() { printf "${C_YELLOW}!${C_RESET} %s\n" "$*" >&2; }
err()  { printf "${C_RED}✗${C_RESET} %s\n" "$*" >&2; }

# Current stage label — surfaced by the error handler so failures point at a phase.
STAGE="startup"
step() { STAGE="$*"; printf "\n${C_BOLD}${C_BLUE}== %s ==${C_RESET}\n" "$*"; }

# xtrace toggles for --debug. trace_off is always safe to call; trace_on only
# re-enables tracing when --debug is active. Used to keep secrets out of `set -x`.
trace_off() { { set +x; } 2>/dev/null; }
trace_on()  { if ${DEBUG:-false}; then set -x; fi; }

# Single-shot error handler. Disables the trap and xtrace on the first line so it
# cannot re-fire from inside itself or from subshells (errtrace), reports the
# failing stage exactly once, then exits.
_ERR_HANDLED=false
on_error() {
  trap - ERR
  { set +x; } 2>/dev/null
  if $_ERR_HANDLED; then exit 1; fi
  _ERR_HANDLED=true
  err "Setup failed during '${STAGE}' (line $1)."
  cat <<EOF >&2

Common fixes:
  - Docker not running               → start Docker Desktop, then re-run.
  - Port already used                → setup auto-picks a free port; pass --mysql-port / --backend-port / --frontend-port to force one.
  - MySQL connection failed          → check docker/.env credentials and 'docker compose -f docker/docker-compose.yml ps'.
  - Prisma migration failed          → 'cd backend && npx prisma migrate status' for details.
  - Permission denied on setup.sh    → 'chmod +x scripts/setup.sh' or run 'bash scripts/setup.sh'.
EOF
  exit 1
}
trap 'on_error $LINENO' ERR

# ──────────────────────────────────────────────────────────────────────────────
# Defaults
# ──────────────────────────────────────────────────────────────────────────────
DEFAULT_MYSQL_PORT=3306
DEFAULT_BACKEND_PORT=5001
DEFAULT_FRONTEND_PORT=5173
DEFAULT_DB_NAME="textile_pos"
DEFAULT_DB_USER="textile_pos"
DEFAULT_BASE_CURRENCY="USD"
DEFAULT_COMPANY_NAME="Textile & POS ERP"
DEFAULT_ADMIN_USERNAME="admin"
DEFAULT_ADMIN_EMAIL="admin@textilepos.local"
DEFAULT_ADMIN_NAME="Administrator"

# Inputs (empty means "ask / derive").
MYSQL_PORT=""
BACKEND_PORT=""
FRONTEND_PORT=""
DB_NAME=""
DB_USER=""
DB_PASSWORD=""
DB_ROOT_PASSWORD=""
ADMIN_NAME=""
ADMIN_EMAIL=""
ADMIN_USERNAME=""
ADMIN_PASSWORD=""
BASE_CURRENCY=""
COMPANY_NAME=""
ASSUME_YES=false
SKIP_INSTALL=false
SKIP_DOCKER=false
SKIP_MIGRATE=false
SKIP_SEED=false
WITH_DEV_DATA=false
RESET_ADMIN_PASSWORD=false
ALLOW_ROOT_DB_USER=false
DEBUG=false

ADMIN_PASSWORD_AUTOGENERATED=false
DB_USE_ROOT=false

# ──────────────────────────────────────────────────────────────────────────────
# Flag parsing
# ──────────────────────────────────────────────────────────────────────────────
print_help() {
  cat <<EOF
textile-pos setup script

Usage: npm run setup -- [flags]

Required-when-empty inputs (prompted interactively unless --yes is passed):
  --mysql-port <n>          MySQL host port    (default $DEFAULT_MYSQL_PORT)
  --backend-port <n>        Backend HTTP port  (default $DEFAULT_BACKEND_PORT)
  --frontend-port <n>       Frontend dev port  (default $DEFAULT_FRONTEND_PORT)
  --db-name <name>          Database name      (default $DEFAULT_DB_NAME)
  --db-user <name>          DB user            (default $DEFAULT_DB_USER)
  --db-password <pw>        DB password        (generated if missing)
  --db-root-password <pw>   MySQL root pw      (generated if missing)
  --admin-name <name>       Admin display name (default $DEFAULT_ADMIN_NAME)
  --admin-email <email>     Admin email        (default $DEFAULT_ADMIN_EMAIL)
  --admin-username <u>      Admin username     (default $DEFAULT_ADMIN_USERNAME)
  --admin-password <pw>     Admin password     (generated if missing)
  --base-currency <code>    Base currency      (default $DEFAULT_BASE_CURRENCY)
  --company-name <name>     Shop / company     (default "$DEFAULT_COMPANY_NAME")

Behaviour flags:
  --yes                     Non-interactive; use defaults / generated values.
  --skip-install            Skip npm install steps.
  --skip-docker             Skip docker compose up / health check.
  --skip-migrate            Skip prisma migrate deploy.
  --skip-seed               Skip prisma db seed.
  --with-dev-data           Also seed demo/sample data (products, suppliers, customers). Off by default.
  --reset-admin-password    Force-update existing admin password to --admin-password.
  --allow-root-db-user      Permit 'root' as the application DB user (not recommended).
  --debug                   Verbose tracing (set -x); never prints passwords/secrets.
  -h | --help               Show this help.
EOF
}

require_value() {
  if [ -z "${2-}" ] || [[ "${2}" == --* ]]; then
    err "Flag $1 requires a value."
    exit 2
  fi
}

while [ $# -gt 0 ]; do
  case "$1" in
    --mysql-port)            require_value "$1" "${2-}"; MYSQL_PORT="$2"; shift 2 ;;
    --backend-port)          require_value "$1" "${2-}"; BACKEND_PORT="$2"; shift 2 ;;
    --frontend-port)         require_value "$1" "${2-}"; FRONTEND_PORT="$2"; shift 2 ;;
    --db-name)               require_value "$1" "${2-}"; DB_NAME="$2"; shift 2 ;;
    --db-user)               require_value "$1" "${2-}"; DB_USER="$2"; shift 2 ;;
    --db-password)           require_value "$1" "${2-}"; DB_PASSWORD="$2"; shift 2 ;;
    --db-root-password)      require_value "$1" "${2-}"; DB_ROOT_PASSWORD="$2"; shift 2 ;;
    --admin-name)            require_value "$1" "${2-}"; ADMIN_NAME="$2"; shift 2 ;;
    --admin-email)           require_value "$1" "${2-}"; ADMIN_EMAIL="$2"; shift 2 ;;
    --admin-username)        require_value "$1" "${2-}"; ADMIN_USERNAME="$2"; shift 2 ;;
    --admin-password)        require_value "$1" "${2-}"; ADMIN_PASSWORD="$2"; shift 2 ;;
    --base-currency)         require_value "$1" "${2-}"; BASE_CURRENCY="$2"; shift 2 ;;
    --company-name)          require_value "$1" "${2-}"; COMPANY_NAME="$2"; shift 2 ;;
    --yes)                   ASSUME_YES=true; shift ;;
    --skip-install)          SKIP_INSTALL=true; shift ;;
    --skip-docker)           SKIP_DOCKER=true; shift ;;
    --skip-migrate)          SKIP_MIGRATE=true; shift ;;
    --skip-seed)             SKIP_SEED=true; shift ;;
    --with-dev-data)         WITH_DEV_DATA=true; shift ;;
    --reset-admin-password)  RESET_ADMIN_PASSWORD=true; shift ;;
    --allow-root-db-user)    ALLOW_ROOT_DB_USER=true; shift ;;
    --debug)                 DEBUG=true; shift ;;
    -h|--help)               print_help; exit 0 ;;
    *) err "Unknown argument: $1"; print_help; exit 2 ;;
  esac
done

if $DEBUG; then
  info "Debug mode enabled (passwords and secrets are never traced)."
  set -x
fi

# ──────────────────────────────────────────────────────────────────────────────
# Prerequisites
# ──────────────────────────────────────────────────────────────────────────────
step "Checking prerequisites"
need_bin() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Required command not found: $1"
    exit 1
  fi
  ok "$1 found"
}
need_bin node
need_bin npm

if ! $SKIP_DOCKER; then
  need_bin docker
  if ! docker compose version >/dev/null 2>&1; then
    err "'docker compose' v2 plugin is required. Update Docker Desktop or install the compose plugin."
    exit 1
  fi
  ok "docker compose found"

  if ! docker info >/dev/null 2>&1; then
    err "Docker is installed but not running. Start Docker Desktop and re-run."
    exit 1
  fi
  ok "docker daemon reachable"
fi

# ──────────────────────────────────────────────────────────────────────────────
# Interactive prompts (only if missing AND --yes is not set AND we have a tty)
# ──────────────────────────────────────────────────────────────────────────────
has_tty() { [ -t 0 ]; }
prompt_value() {
  # $1=var name to set, $2=label, $3=default value
  local __var="$1" __label="$2" __default="$3" __input=""
  if $ASSUME_YES || ! has_tty; then
    eval "$__var=\"\${$__var:-$__default}\""
    return
  fi
  local __current; eval "__current=\"\${$__var-}\""
  if [ -n "$__current" ]; then return; fi
  read -r -p "$__label [$__default]: " __input || true
  eval "$__var=\"\${__input:-$__default}\""
}

prompt_password() {
  # $1=var name, $2=label. Single exit path so xtrace (--debug) is reliably
  # restored, and so secret comparisons are never echoed by `set -x`.
  local __var="$1" __label="$2" __input="" __confirm="" __current=""
  trace_off
  if ! $ASSUME_YES && has_tty; then
    eval "__current=\"\${$__var-}\""
    if [ -z "$__current" ]; then
      while true; do
        read -r -s -p "$__label (min 8 chars, blank = auto-generate): " __input; echo
        if [ -z "$__input" ]; then eval "$__var=\"\""; break; fi
        if [ "${#__input}" -lt 8 ]; then warn "Too short, try again."; continue; fi
        read -r -s -p "Confirm: " __confirm; echo
        if [ "$__input" != "$__confirm" ]; then warn "Did not match, try again."; continue; fi
        eval "$__var=\"$__input\""; break
      done
    fi
  fi
  trace_on
}

step "Collecting configuration"
prompt_value    MYSQL_PORT       "MySQL host port"        "$DEFAULT_MYSQL_PORT"
prompt_value    BACKEND_PORT     "Backend HTTP port"      "$DEFAULT_BACKEND_PORT"
prompt_value    FRONTEND_PORT    "Frontend dev port"      "$DEFAULT_FRONTEND_PORT"
prompt_value    DB_NAME          "Database name"          "$DEFAULT_DB_NAME"
prompt_value    DB_USER          "Database user"          "$DEFAULT_DB_USER"
prompt_password DB_PASSWORD      "Database password"
prompt_password DB_ROOT_PASSWORD "MySQL root password"
prompt_value    COMPANY_NAME     "Company / shop name"    "$DEFAULT_COMPANY_NAME"
prompt_value    BASE_CURRENCY    "Base currency code"     "$DEFAULT_BASE_CURRENCY"
prompt_value    ADMIN_NAME       "Admin display name"     "$DEFAULT_ADMIN_NAME"
prompt_value    ADMIN_USERNAME   "Admin username"         "$DEFAULT_ADMIN_USERNAME"
prompt_value    ADMIN_EMAIL      "Admin email"            "$DEFAULT_ADMIN_EMAIL"
prompt_password ADMIN_PASSWORD   "Admin password"

# Apply final fall-through defaults (covers --yes / non-tty paths).
MYSQL_PORT="${MYSQL_PORT:-$DEFAULT_MYSQL_PORT}"
BACKEND_PORT="${BACKEND_PORT:-$DEFAULT_BACKEND_PORT}"
FRONTEND_PORT="${FRONTEND_PORT:-$DEFAULT_FRONTEND_PORT}"
DB_NAME="${DB_NAME:-$DEFAULT_DB_NAME}"
DB_USER="${DB_USER:-$DEFAULT_DB_USER}"
ADMIN_NAME="${ADMIN_NAME:-$DEFAULT_ADMIN_NAME}"
ADMIN_EMAIL="${ADMIN_EMAIL:-$DEFAULT_ADMIN_EMAIL}"
ADMIN_USERNAME="${ADMIN_USERNAME:-$DEFAULT_ADMIN_USERNAME}"
BASE_CURRENCY="$(echo "${BASE_CURRENCY:-$DEFAULT_BASE_CURRENCY}" | tr '[:lower:]' '[:upper:]')"
COMPANY_NAME="${COMPANY_NAME:-$DEFAULT_COMPANY_NAME}"

# ──────────────────────────────────────────────────────────────────────────────
# Secret generation
# ──────────────────────────────────────────────────────────────────────────────
read_env_value() {
  # $1=file $2=key -> echoes the stored value (surrounding quotes stripped), or "".
  # Used to reuse secrets across reruns so DB credentials stay stable.
  local file="$1" key="$2" line=""
  [ -f "$file" ] || { printf '%s' ""; return 0; }
  line="$(grep -E -m1 "^${key}=" "$file" 2>/dev/null || true)"
  line="${line#*=}"
  line="${line%\"}"; line="${line#\"}"
  printf '%s' "$line"
}

gen_secret() {
  # URL-safe alnum (so DATABASE_URL and other strings need no encoding).
  # Run in a subshell with pipefail OFF: `head -c N` closes the pipe after N
  # bytes, so `tr` exits 141 (SIGPIPE). With pipefail on, that 141 became the
  # pipeline status and tripped `set -e`; disabling it makes the status head's 0.
  # `set +x` keeps the generated value out of any --debug trace.
  ( set +o pipefail; set +x; LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-24}" )
}

trace_off  # secret generation/reuse must never appear in --debug output
# Reuse secrets a previous run already wrote so re-running setup keeps the same DB
# credentials (the MySQL volume was initialized with them) and the same JWT/session
# secrets. Only generate when truly absent. Generated lengths exceed the documented
# minimums: DB/root >=16, admin >=12, JWT/session strong (48); manual passwords are
# validated in prompt_password.
if [ -z "$DB_PASSWORD" ]; then
  DB_PASSWORD="$(read_env_value "$DOCKER_ENV" MYSQL_PASSWORD)"
  if [ -n "$DB_PASSWORD" ]; then info "Reusing existing DB password from docker/.env."
  else DB_PASSWORD="$(gen_secret 24)"; info "Generated random DB password (24 chars)."; fi
fi
if [ -z "$DB_ROOT_PASSWORD" ]; then
  DB_ROOT_PASSWORD="$(read_env_value "$DOCKER_ENV" MYSQL_ROOT_PASSWORD)"
  if [ -n "$DB_ROOT_PASSWORD" ]; then info "Reusing existing MySQL root password from docker/.env."
  else DB_ROOT_PASSWORD="$(gen_secret 24)"; info "Generated random MySQL root password (24 chars)."; fi
fi
JWT_SECRET="$(read_env_value "$BACKEND_ENV" JWT_SECRET)";         [ -n "$JWT_SECRET" ]     || JWT_SECRET="$(gen_secret 48)"
SESSION_SECRET="$(read_env_value "$BACKEND_ENV" SESSION_SECRET)"; [ -n "$SESSION_SECRET" ] || SESSION_SECRET="$(gen_secret 48)"

if [ -z "$ADMIN_PASSWORD" ]; then
  ADMIN_PASSWORD="$(read_env_value "$BACKEND_ENV" SEED_ADMIN_PASSWORD)"
  if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="$(gen_secret 16)"
    ADMIN_PASSWORD_AUTOGENERATED=true
  fi
elif [ "${#ADMIN_PASSWORD}" -lt 8 ]; then
  err "Admin password must be at least 8 characters."
  exit 2
fi
trace_on

# ──────────────────────────────────────────────────────────────────────────────
# DB user safety — discourage using the MySQL root account as the app DB user
# ──────────────────────────────────────────────────────────────────────────────
if [ "$DB_USER" = "root" ]; then
  if $ALLOW_ROOT_DB_USER; then
    DB_USE_ROOT=true
    warn "Using 'root' as the application DB user (forced via --allow-root-db-user)."
  elif $ASSUME_YES || ! has_tty; then
    warn "Using 'root' as the application DB user is not recommended — switching to '$DEFAULT_DB_USER'."
    warn "Pass --allow-root-db-user to override."
    DB_USER="$DEFAULT_DB_USER"
  else
    warn "Using 'root' as the application DB user is not recommended."
    read -r -p "Use '$DEFAULT_DB_USER' instead? [Y/n]: " __root_ans || true
    case "${__root_ans:-Y}" in
      [Nn]*) DB_USE_ROOT=true; warn "Keeping 'root' as the DB user at your request." ;;
      *)     DB_USER="$DEFAULT_DB_USER"; ok "Switched DB user to '$DB_USER'." ;;
    esac
  fi
fi

if $DB_USE_ROOT; then
  # mysql:8.0 refuses MYSQL_USER=root, so the app connects as the real root
  # account: reuse the root password and skip MYSQL_USER/PASSWORD in docker/.env.
  DB_PASSWORD="$DB_ROOT_PASSWORD"
fi

# ──────────────────────────────────────────────────────────────────────────────
# Port availability — auto-pick alternates if requested ones are busy
# ──────────────────────────────────────────────────────────────────────────────
port_in_use() {
  local p="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -i "tcp:$p" -sTCP:LISTEN >/dev/null 2>&1 && return 0
    return 1
  fi
  # Fallback: try /dev/tcp (bash-builtin). 0 = open (in use).
  ( exec 3<>"/dev/tcp/127.0.0.1/$p" ) >/dev/null 2>&1 && { exec 3>&-; return 0; }
  return 1
}

resolve_port() {
  # $1=label, $2=requested port -> echoes chosen port
  local label="$1" requested="$2" port="$2" tries=0
  while port_in_use "$port"; do
    warn "Port $port is busy. Trying $((port+1))…" >&2
    port=$((port+1)); tries=$((tries+1))
    if [ $tries -ge 50 ]; then
      err "Could not find a free $label port near $requested."
      exit 1
    fi
  done
  if [ "$port" != "$requested" ]; then
    warn "$label port $requested unavailable — using $port instead." >&2
  fi
  echo "$port"
}

step "Checking ports"
MYSQL_PORT="$(resolve_port "MySQL"    "$MYSQL_PORT")"
BACKEND_PORT="$(resolve_port "Backend" "$BACKEND_PORT")"
FRONTEND_PORT="$(resolve_port "Frontend" "$FRONTEND_PORT")"
ok "MySQL    → $MYSQL_PORT"
ok "Backend  → $BACKEND_PORT"
ok "Frontend → $FRONTEND_PORT"

# ──────────────────────────────────────────────────────────────────────────────
# .env writers — preserve unrelated existing keys
# ──────────────────────────────────────────────────────────────────────────────
upsert_env_var() {
  local file="$1" key="$2" value="$3"
  mkdir -p "$(dirname "$file")"
  touch "$file"
  if grep -qE "^${key}=" "$file" 2>/dev/null; then
    awk -v k="$key" -v v="$value" 'BEGIN{FS="="; OFS=""}
      {
        if (index($0, k"=") == 1) { print k"="v } else { print $0 }
      }' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

step "Writing environment files"
trace_off  # env files hold secrets — keep them out of any --debug trace

# DATABASE_URL — values are URL-safe alnum, no encoding needed.
DATABASE_URL="mysql://${DB_USER}:${DB_PASSWORD}@localhost:${MYSQL_PORT}/${DB_NAME}"

# backend/.env
upsert_env_var "$BACKEND_ENV" "NODE_ENV"                  "development"
upsert_env_var "$BACKEND_ENV" "PORT"                      "$BACKEND_PORT"
upsert_env_var "$BACKEND_ENV" "DATABASE_URL"              "\"$DATABASE_URL\""
upsert_env_var "$BACKEND_ENV" "JWT_SECRET"                "\"$JWT_SECRET\""
upsert_env_var "$BACKEND_ENV" "JWT_EXPIRES_IN"            "8h"
upsert_env_var "$BACKEND_ENV" "SESSION_SECRET"            "\"$SESSION_SECRET\""
upsert_env_var "$BACKEND_ENV" "CORS_ORIGIN"               "http://localhost:${FRONTEND_PORT}"
upsert_env_var "$BACKEND_ENV" "STORAGE_PATH"              "./storage"
upsert_env_var "$BACKEND_ENV" "BASE_CURRENCY_CODE"        "$BASE_CURRENCY"
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_NAME"           "\"$ADMIN_NAME\""
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_USERNAME"       "$ADMIN_USERNAME"
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_EMAIL"          "$ADMIN_EMAIL"
upsert_env_var "$BACKEND_ENV" "SEED_ADMIN_PASSWORD"       "\"$ADMIN_PASSWORD\""
upsert_env_var "$BACKEND_ENV" "SEED_COMPANY_NAME"         "\"$COMPANY_NAME\""
upsert_env_var "$BACKEND_ENV" "SEED_BASE_CURRENCY"        "$BASE_CURRENCY"
upsert_env_var "$BACKEND_ENV" "SEED_RESET_ADMIN_PASSWORD" "$([ "$RESET_ADMIN_PASSWORD" = true ] && echo true || echo false)"
ok "Wrote $BACKEND_ENV"

# frontend/.env
upsert_env_var "$FRONTEND_ENV" "VITE_API_URL"       "/api/v1"
upsert_env_var "$FRONTEND_ENV" "VITE_API_BASE_URL"  "http://localhost:${BACKEND_PORT}/api/v1"
upsert_env_var "$FRONTEND_ENV" "VITE_BACKEND_PORT"  "$BACKEND_PORT"
ok "Wrote $FRONTEND_ENV"

# docker/.env
upsert_env_var "$DOCKER_ENV" "MYSQL_DATABASE"       "$DB_NAME"
if $DB_USE_ROOT; then
  info "Skipping MYSQL_USER/MYSQL_PASSWORD — the app connects as the root account."
else
  upsert_env_var "$DOCKER_ENV" "MYSQL_USER"         "$DB_USER"
  upsert_env_var "$DOCKER_ENV" "MYSQL_PASSWORD"     "$DB_PASSWORD"
fi
upsert_env_var "$DOCKER_ENV" "MYSQL_ROOT_PASSWORD"  "$DB_ROOT_PASSWORD"
upsert_env_var "$DOCKER_ENV" "MYSQL_PORT"           "$MYSQL_PORT"
ok "Wrote $DOCKER_ENV"
trace_on

if $DEBUG; then
  info "Resolved configuration (secrets hidden):"
  printf '   mysql_port=%s  backend_port=%s  frontend_port=%s\n' "$MYSQL_PORT" "$BACKEND_PORT" "$FRONTEND_PORT"
  printf '   db_name=%s  db_user=%s  base_currency=%s\n'         "$DB_NAME" "$DB_USER" "$BASE_CURRENCY"
  printf '   company=%s  admin_user=%s  admin_email=%s\n'        "$COMPANY_NAME" "$ADMIN_USERNAME" "$ADMIN_EMAIL"
fi

# ──────────────────────────────────────────────────────────────────────────────
# MySQL credential helpers (verify access; reconcile non-destructively if needed)
# ──────────────────────────────────────────────────────────────────────────────
# Run mysql inside the db container as $1 with password $2 (SQL from stdin).
# The password is passed via MYSQL_PWD — never on the command line — so empty
# passwords work and nothing leaks into the container's process list.
db_mysql() {
  (cd "$ROOT_DIR/docker" && docker compose exec -T -e "MYSQL_PWD=$2" db mysql -u"$1")
}
# True when the given user/password can authenticate to the server at all.
db_can_connect() {
  printf 'SELECT 1;\n' | db_mysql "$1" "$2" >/dev/null 2>&1
}
# True when the given user/password can actually USE the target database ($3).
# This is what the app needs — server-level auth alone isn't enough (the user may
# exist but lack a grant on this database, or the database may not exist yet).
db_can_access_db() {
  printf 'SELECT 1;\n' | (cd "$ROOT_DIR/docker" && docker compose exec -T -e "MYSQL_PWD=$2" db mysql -u"$1" "$3") >/dev/null 2>&1
}
# Escape a value for use inside a single-quoted MySQL string literal.
sql_quote() { printf '%s' "$1" | sed "s/'/''/g"; }

# ──────────────────────────────────────────────────────────────────────────────
# Docker MySQL
# ──────────────────────────────────────────────────────────────────────────────
if ! $SKIP_DOCKER; then
  step "Starting MySQL"
  (cd "$ROOT_DIR/docker" && docker compose up -d)
  ok "docker compose up -d issued"

  step "Waiting for MySQL"
  CID=""; tries=0; HEALTH=""
  while [ $tries -lt 60 ]; do
    CID="$(cd "$ROOT_DIR/docker" && docker compose ps -q db 2>/dev/null || true)"
    if [ -n "$CID" ]; then
      HEALTH="$(docker inspect --format='{{.State.Health.Status}}' "$CID" 2>/dev/null || echo "")"
      if [ "$HEALTH" = "healthy" ]; then ok "MySQL is healthy."; break; fi
      # No usable healthcheck status — fall back to a direct ping in the container.
      if [ -z "$HEALTH" ] || [ "$HEALTH" = "unknown" ] || [ "$HEALTH" = "<no value>" ]; then
        if (cd "$ROOT_DIR/docker" && docker compose exec -T db mysqladmin ping -h localhost --silent) >/dev/null 2>&1; then
          ok "MySQL responded to ping."; HEALTH="healthy"; break
        fi
      fi
    fi
    tries=$((tries+1)); sleep 2
  done
  if [ "${HEALTH:-}" != "healthy" ]; then
    err "MySQL did not become ready in time. Check 'docker compose -f docker/docker-compose.yml logs db'."
    exit 1
  fi

  # `mysqladmin ping` reports "alive" even when credentials are wrong, so verify the
  # configured login actually works before Prisma does (and gives a cryptic error).
  step "Verifying database access"
  trace_off  # this block handles the DB password
  if db_can_access_db "$DB_USER" "$DB_PASSWORD" "$DB_NAME"; then
    ok "Database access verified: '$DB_USER' can use '$DB_NAME'."
  else
    # A pre-existing data volume keeps the credentials it was first initialized with,
    # so a freshly-configured user/password may not exist yet. Try to get in as root
    # and create the database + user (or fix root's password) — without losing data.
    warn "Configured credentials for '$DB_USER' were rejected — reconciling via root (non-destructive)…"
    ROOT_PW=""; ROOT_OK=false
    for __cand in "$DB_ROOT_PASSWORD" "textile_root_pwd" ""; do
      if db_can_connect root "$__cand"; then ROOT_PW="$__cand"; ROOT_OK=true; break; fi
    done
    if $ROOT_OK; then
      __pw="$(sql_quote "$DB_PASSWORD")"
      if $DB_USE_ROOT; then
        printf "CREATE DATABASE IF NOT EXISTS \`%s\`;\nALTER USER 'root'@'%%' IDENTIFIED BY '%s';\nFLUSH PRIVILEGES;\n" \
          "$DB_NAME" "$__pw" | db_mysql root "$ROOT_PW" >/dev/null 2>&1 || true
      else
        printf "CREATE DATABASE IF NOT EXISTS \`%s\`;\nCREATE USER IF NOT EXISTS '%s'@'%%' IDENTIFIED BY '%s';\nALTER USER '%s'@'%%' IDENTIFIED BY '%s';\nGRANT ALL PRIVILEGES ON \`%s\`.* TO '%s'@'%%';\nFLUSH PRIVILEGES;\n" \
          "$DB_NAME" "$DB_USER" "$__pw" "$DB_USER" "$__pw" "$DB_NAME" "$DB_USER" \
          | db_mysql root "$ROOT_PW" >/dev/null 2>&1 || true
      fi
      if db_can_access_db "$DB_USER" "$DB_PASSWORD" "$DB_NAME"; then
        ok "Reconciled existing MySQL: '$DB_USER' can now access '$DB_NAME' (existing data preserved)."
      else
        trace_on
        err "Reached MySQL as root but could not grant '$DB_USER' access to '$DB_NAME'."
        warn "Reset the volume (DELETES its data): docker compose -f docker/docker-compose.yml down -v && npm run setup"
        exit 1
      fi
    else
      trace_on
      err "MySQL is up but no known root password works against the existing data volume."
      warn "The volume was initialized by an earlier run with credentials this setup doesn't have."
      warn "Reset the volume (DELETES its data): docker compose -f docker/docker-compose.yml down -v && npm run setup"
      exit 1
    fi
  fi
  trace_on
else
  info "Skipping docker compose (--skip-docker)."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Install dependencies
# ──────────────────────────────────────────────────────────────────────────────
if ! $SKIP_INSTALL; then
  step "Installing dependencies"
  (cd "$ROOT_DIR" && npm install)
  ok "Dependencies installed"
else
  info "Skipping npm install (--skip-install)."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Prisma: generate → migrate deploy → seed (run from backend/, where the schema lives)
# ──────────────────────────────────────────────────────────────────────────────
step "Running Prisma migrations"
(cd "$ROOT_DIR/backend" && npx prisma generate)
ok "Prisma client generated"

if ! $SKIP_MIGRATE; then
  (cd "$ROOT_DIR/backend" && npx prisma migrate deploy)
  ok "Migrations applied"
else
  info "Skipping migrations (--skip-migrate)."
fi

if ! $SKIP_SEED; then
  if $WITH_DEV_DATA; then
    step "Running seed (standard system data + dev/demo data)"
    info "Running standard system seed, then dev/demo data (--with-dev-data)."
    (cd "$ROOT_DIR/backend" && SEED_DEV_DATA=true npx prisma db seed)
  else
    step "Running seed (standard system data only)"
    info "Running standard system seed. Skipping dev/demo data (pass --with-dev-data to include it)."
    (cd "$ROOT_DIR/backend" && npx prisma db seed)
  fi
  ok "Seed complete"
else
  info "Skipping seed (--skip-seed)."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────────────
step "Setup complete"
cat <<EOF
${C_BOLD}Service URLs${C_RESET}
  Frontend:  http://localhost:${FRONTEND_PORT}
  Backend:   http://localhost:${BACKEND_PORT}/api/v1
  MySQL:     localhost:${MYSQL_PORT}  (db: ${DB_NAME}, user: ${DB_USER})

${C_BOLD}Generated files${C_RESET}
  - backend/.env
  - frontend/.env
  - docker/.env

${C_BOLD}Next step${C_RESET}
  npm run dev
EOF

if $ADMIN_PASSWORD_AUTOGENERATED; then
  trace_off  # do not echo the generated admin password under --debug
  echo
  warn "An admin password was auto-generated. Save it now — it is shown once."
  echo "${C_BOLD}  username: ${ADMIN_USERNAME}"
  echo "  password: ${ADMIN_PASSWORD}${C_RESET}"
fi
